host: ''

port: 8317

tls:
  enable: false
  cert: ''
  key: ''

remote-management:
  allow-remote: true
  secret-key: '123456'

auth-dir: '~/.cli-proxy-api'

api-keys:
  - 'sk-173e1dadc4ebb2ce-v4m1xl-d8b35119'

debug: false

logging-to-file: false

usage-statistics-enabled: true

show-provider-prefixes: true

disable-auth: false

use-canonical-translator: true
